version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:secureorpheus123@db:5432/app_development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secureorpheus123
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - hcer_public_gh_data_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secureorpheus123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app_development
    ports:
      - "5432:5432"

volumes:
  hcer_public_gh_data_postgres_data:
  bundle_cache: 